services:
  traefik:
    extends:
      file: ./traefik/docker-compose.yml
      service: traefik

  backend:
    extends:
      file: ./backend/docker-compose.yml
      service: backend
    env_file:
      - ../env/backend/.env

  frontend:
    extends:
      file: ./frontend/docker-compose.yml
      service: frontend

  db:
    extends:
      file: ./db/docker-compose.yml
      service: db
    env_file:
      - ../env/infra/db/.env

#  minio:
#    extends:
#      file: ./minio/docker-compose.yml
#      service: minio
#    env_file:
#      - ../env/infra/minio/.env

  portainer:
    extends:
      file: ./portainer/docker-compose.yml
      service: portainer

  uptime-kuma:
    extends:
      file: ./uptime-kuma/docker-compose.yml
      service: uptime-kuma

volumes:
  portainer_data:
  minio-data:
  pgdata:
  uptime-kuma-data:

networks:
  pourymovie:
    name: pourymovie