services:
  backend:
    restart: always
    build:
      context: ../../backend
    ports:
      - "1406:1406"
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - pourymovie
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-router.rule=Host(`api.pourymovie.ir`)"
      - "traefik.http.routers.backend-router.entrypoints=websecure"
      - "traefik.http.routers.backend-router.tls.certresolver=myResolver"
      - "traefik.http.routers.backend-router.service=backend-service"
      - "traefik.http.routers.backend-router-http.rule=Host(`api.pourymovie.ir`)"
      - "traefik.http.routers.backend-router-http.entrypoints=web"
      - "traefik.http.routers.backend-router-http.service=backend-service"
      - "traefik.http.routers.backend-router-http.middlewares=redirect-to-https"
      - "traefik.http.services.backend-service.loadbalancer.server.port=1406"


