services:
  docker-socket:
    image: tecnativa/docker-socket-proxy
    restart: always
    ports:
      - "2375:2375"
    environment:
      CONTAINERS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - pourymovie