http:
  routers:
    frontend-router-http:
      rule: "Host(`pourymovie.ir`)"
      entryPoints: [web]
      service: frontend-service

    frontend-router:
      rule: "Host(`pourymovie.ir`)"
      entryPoints: [websecure]
      tls:
        certResolver: letsencrypt
      service: frontend-service

    backend-router-http:
      rule: "Host(`api.pourymovie.ir`)"
      entryPoints: [web]
      middlewares: [redirect-to-https]
      service: backend-service

    backend-router:
      rule: "Host(`api.pourymovie.ir`)"
      entryPoints: [websecure]
      tls:
        certResolver: letsencrypt
      service: backend-service

    portainer-router-http:
      rule: "Host(`portainer.pourymovie.ir`)"
      entryPoints: [web]
      middlewares: [redirect-to-https]
      service: portainer-service

    portainer-router:
      rule: "Host(`portainer.pourymovie.ir`)"
      entryPoints: [websecure]
      tls:
        certResolver: letsencrypt
      service: portainer-service

    minio-router-http:
      rule: "Host(`minio.pourymovie.ir`)"
      entryPoints: [web]
      middlewares: [redirect-to-https]
      service: minio-service

    minio-router:
      rule: "Host(`minio.pourymovie.ir`)"
      entryPoints: [websecure]
      tls:
        certResolver: letsencrypt
      service: minio-service

    swagger-router-http:
      rule: "Host(`swagger.pourymovie.ir`)"
      entryPoints: [web]
      middlewares: [redirect-to-https]
      service: swagger-service

    swagger-router:
      rule: "Host(`swagger.pourymovie.ir`)"
      entryPoints: [websecure]
      tls:
        certResolver: letsencrypt
      service: backend-service
      middlewares:
        - swagger-path-rewrite