http:
  routers:
    frontend-router:
      rule: "Host(`pourymovie.ir`)"
      entryPoints: [websecure]
      tls:
        certResolver: letsencrypt
      service: frontend-service

    backend-router:
      rule: "Host(`api.pourymovie.ir`)"
      entryPoints: [websecure]
      tls:
        certResolver: letsencrypt
      service: backend-service

    portainer-router:
      rule: "Host(`portainer.pourymovie.ir`)"
      entryPoints: [websecure]
      tls:
        certResolver: letsencrypt
      service: portainer-service

#    minio-router:
#      rule: "Host(`minio.pourymovie.ir`)"
#      entryPoints: [websecure]
#      tls:
#        certResolver: letsencrypt
#      service: minio-service

    swagger-router:
      rule: "Host(`swagger.pourymovie.ir`)"
      entryPoints: [websecure]
      tls:
        certResolver: letsencrypt
      service: swagger-service
      middlewares:
        - swagger-path

    backDoc-router:
      rule: "Host(`backDoc.pourymovie.ir`)"
      entryPoints: [websecure]
      tls:
        certResolver: letsencrypt
      service: backDoc-service

    docker-socket-router:
      rule: "Host(`dd.pourymovie.ir`)"
      entryPoints: [websecure]
      tls:
        certResolver: letsencrypt
      service: docker-socket-service
      middlewares:
        - docker-socket-whitelist

    http-to-https:
      entryPoints:
        - web
      rule: "HostRegexp(`{host:.+}`)"
      middlewares:
        - redirect-to-https
      service: noop@internal
      priority:  1