http:
  routers:
    backend-router:
      rule: "Host(`api.pourymovie.ir`)"
      service: backend-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
    frontend-router:
      rule: "Host(`pourymovie.ir`)"
      service: frontend-service
      entryPoints:
        - websecure
        - web
      tls:
        certResolver: letsencrypt

    portainer-router:
      rule: "Host(`portainer.pourymovie.ir`)"
      service: portainer-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    minio-router:
      rule: "Host(`minio.pourymovie.ir`)"
      service: minio-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    swagger-router:
      rule: "Host(`swagger.pourymovie.ir`)"
      service: swagger-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    backend-service:
      loadBalancer:
        servers:
          - url: "http://backend:1406"

    swagger-service:
      loadBalancer:
        servers:
          - url: "http://backend:1406/apiDocs/v1"

    frontend-service:
      loadBalancer:
        servers:
          - url: "http://frontend:3000"

    portainer-service:
      loadBalancer:
        servers:
          - url: "http://portainer:9000"

    minio-service:
      loadBalancer:
        servers:
          - url: "http://minioProd:9001"
