name: Infrastructure CI
description: CI workflow for the infrastructure service

on:
  push:
    branches:
      - main
      - develop
      - release/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Copy code to /opt/pourymovie/infra
        run: |
          sudo rm -rf /opt/pourymovie/infra/*
          sudo cp -r . /opt/pourymovie/infra

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Run deployment script
        run: |
          sudo chmod +x /opt/pourymovie/infra/redeploy.sh
          sudo /opt/pourymovie/infra/redeploy.sh
